### ISSUE TITLE
Auth with private key file

### ISSUE THREAD

**Issue by Bonczidai** [openscore/score-actions#24]
when we use the SSH action with private key file we have to supply the password input which is required (may be empty in this case). 

Is it possible to change its required property to false so we would not have to pass an empty string every time?

**Comment by ioanvranau** [comment]
@Bonczidai how often this issue is happening? It will help your flows to be a lot more clear?

**Comment by Bonczidai** [comment]
I think  I can live with this.. we can skip this for now

**Comment by ioanvranau** [comment]
We can skip, but if you think that this issue is happening very often, probably we will add some value with that.

**Comment by ioanvranau** [comment]
I removed the required option from password field, but we will need to wait for another release of ssh in order to use the new behavior. Most probably it is not needed a new release just for this small fix and we will wait for more fixes/ enhancements in order to do that.

@Bonczidai you can decide to close or not this issue or wait until a new release is up.

**Comment by Bonczidai** [comment]
Great.. thanks

Since the issue is minor I am closing it..

**Comment by Bonczidai** [comment]
fixed in future release
